version: 2.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:17.0
    steps:
      - checkout
      - run:
          name: Install Dependencies and Run Tests
          command: |-
            sudo apt-get update && sudo apt-get install -y xvfb libxtst6 libxi6
            Xvfb :99 -screen 0 1024x768x16 &
            export DISPLAY=:99
            mvn verify
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository

workflows:
  build-and-test:
    jobs:
      - test-java
